var annotated_dup =
[
    [ "AuthPacket", "classAuthPacket.html", "classAuthPacket" ],
    [ "AuthPacketTest", "classAuthPacketTest.html", "classAuthPacketTest" ],
    [ "BasalEndReason", "classBasalEndReason.html", "classBasalEndReason" ],
    [ "BasalType", "classBasalType.html", "classBasalType" ],
    [ "BLEComm", "classBLEComm.html", "classBLEComm" ],
    [ "BleConnection", "structBleConnection.html", "structBleConnection" ],
    [ "CommandType", "classCommandType.html", "classCommandType" ],
    [ "CrcUtil", "classCrcUtil.html", null ],
    [ "Crypt", "classCrypt.html", null ],
    [ "IBLECallback", "classIBLECallback.html", "classIBLECallback" ],
    [ "IPumpDevice", "classIPumpDevice.html", "classIPumpDevice" ],
    [ "IScanCallback", "classIScanCallback.html", "classIScanCallback" ],
    [ "MedtrumBasePacket", "classMedtrumBasePacket.html", "classMedtrumBasePacket" ],
    [ "MedtrumDevice", "classMedtrumDevice.html", "classMedtrumDevice" ],
    [ "MedtrumPumpSync", "classMedtrumPumpSync.html", "classMedtrumPumpSync" ],
    [ "MedtrumTimeUtil", "classMedtrumTimeUtil.html", null ],
    [ "NotificationPacket", "classNotificationPacket.html", "classNotificationPacket" ],
    [ "NotificationPacketTest", "classNotificationPacketTest.html", "classNotificationPacketTest" ],
    [ "PumpBleCallback", "classPumpBleCallback.html", "classPumpBleCallback" ],
    [ "PumpBleComm", "classPumpBleComm.html", "classPumpBleComm" ],
    [ "PumpScanner", "classPumpScanner.html", "classPumpScanner" ],
    [ "PumpService", "classPumpService.html", "classPumpService" ],
    [ "PumpState", "classPumpState.html", "classPumpState" ],
    [ "SetBolusPacket", "classSetBolusPacket.html", "classSetBolusPacket" ],
    [ "SetTempBasalPacket", "classSetTempBasalPacket.html", "classSetTempBasalPacket" ],
    [ "SetTempBasalPacketTest", "classSetTempBasalPacketTest.html", "classSetTempBasalPacketTest" ],
    [ "SubscribePacket", "classSubscribePacket.html", "classSubscribePacket" ],
    [ "SynchronizePacket", "classSynchronizePacket.html", "classSynchronizePacket" ],
    [ "SynchronizePacketTest", "classSynchronizePacketTest.html", "classSynchronizePacketTest" ],
    [ "TestMedtrumBasePacket", "classTestMedtrumBasePacket.html", "classTestMedtrumBasePacket" ],
    [ "WriteCommandPackets", "classWriteCommandPackets.html", "classWriteCommandPackets" ]
];