@startuml inline_umlgraph_1.png
node "InsuBox" {
    package "System Controller" {
        [Controller]
    }

    package "Infra" {
        [EventDispatcher]
    }

    package "Services" {
        [AlgorithmService]
        [PumpService]
        [SensorService]
        [InsuBoxControlService]
    }

    package "Devices" {
        [WavezAlgorithm]
        [MedtrumPump]
        [DexcomG6Sensor]
        [InsuBoxControlBleServices]
        [InsuBoxHMI]
    }

    package "Drivers" {
        [BLEComm]
        [ZephyrBLELibrary]
        [ZephyrGPIO]
    }
}

' System Controller
Controller <-down-> PumpService
Controller <-down-> SensorService
Controller <-down-> InsuBoxControlService
Controller <-down-> AlgorithmService
Controller <--> EventDispatcher

' Services
AlgorithmService -down-> WavezAlgorithm
PumpService -down-> MedtrumPump
SensorService -down-> DexcomG6Sensor
InsuBoxControlService -down-> InsuBoxControlBleServices
InsuBoxControlService -down-> InsuBoxHMI

' Devices
MedtrumPump -down-> BLEComm
MedtrumPump -down-> ZephyrBLELibrary
DexcomG6Sensor -down-> BLEComm
DexcomG6Sensor -down-> ZephyrBLELibrary
InsuBoxControlBleServices -down-> BLEComm
InsuBoxControlBleServices -down-> ZephyrBLELibrary
InsuBoxHMI -down-> ZephyrGPIO

' Peripherals
actor BLE as "BLE"
actor GPIO as "GPIO"

' Drivers
BLEComm -> ZephyrBLELibrary
ZephyrBLELibrary -down-> BLE
ZephyrGPIO -down-> GPIO
@enduml
